### ISSUE TITLE
fitlog可以在windows下使用吗

### ISSUE THREAD

**Issue by houchenyu** [fastnlp/fitlog#10]
我在windows下的anaconda 中安装了fitlog。
fitlog init example初始化时报错
错误信息：
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by yhcc** [comment]
哇，我们没有想到这个问题。在windows上我们可能只能用来查看logs，不能用来管理代码之类的。

**Comment by houchenyu** [comment]
> 哇，我们没有想到这个问题。在windows上我们可能只能用来查看logs，不能用来管理代码之类的。

emmmm, 不用init 项目，也可以用fitlog log在网页端查看logs吗

**Comment by yhcc** [comment]
可以的，自己建一个logs文件。fitlog init只是当需要让fitlog管理代码时需要用的哈。

**Comment by WillQvQ** [comment]
我们这两天可能会做一些更新，争取更多地兼容 Windows（不过不能100%保证功能一致），到时候我在这里再回复您。

**Comment by houchenyu** [comment]
> 我们这两天可能会做一些更新，争取更多地兼容 Windows（不过不能100%保证功能一致），到时候我在这里再回复您。

辛苦你们了，其实我也是主要想试试记录logs的功能，git 可以自己来。

**Comment by houchenyu** [comment]
> 可以的，自己建一个logs文件。fitlog init只是当需要让fitlog管理代码时需要用的哈。

嗯嗯，我试了下可以的。 不过要在开头加`fitlog.set_log_dir('./logs')`。

**Comment by jerryLee80** [comment]
请教。这个地址http://0.0.0.0:5000/，需要自己部署吗？还是fitlog包自动好？

**Comment by xuyige** [comment]
> 请教。这个地址[http://0.0.0.0:5000/，需要自己部署吗？还是fitlog包自动好？](http://0.0.0.0:5000/%EF%BC%8C%E9%9C%80%E8%A6%81%E8%87%AA%E5%B7%B1%E9%83%A8%E7%BD%B2%E5%90%97%EF%BC%9F%E8%BF%98%E6%98%AFfitlog%E5%8C%85%E8%87%AA%E5%8A%A8%E5%A5%BD%EF%BC%9F)

应该是默认本地要么是localhost:5000要么是0.0.0.0:5000等等……可以自己用--ip [your_ip] --port [your_port]来指定

**Comment by softhuafei** [comment]
请问如何在windows上查看远程服务器启动的网页服务呢

**Comment by houchenyu** [comment]
> 请问如何在windows上查看远程服务器启动的网页服务呢

命令行`fitlog log logs`启动后， 输入localhost:5000就可以在浏览器上查看了

**Comment by softhuafei** [comment]
> > 请问如何在windows上查看远程服务器启动的网页服务呢
> 
> 命令行`fitlog log logs`启动后， 输入localhost:5000就可以在浏览器上查看了

感谢回复~不过我的代码是运行在远程服务器的docker里，不知道用什么方法可以在本地访问到服务器上启动的web服务呢?

**Comment by WillQvQ** [comment]
@softhuafei @houchenyu @choosewhatulike 
我们开发了适用于 Windows 的新版本[WindowsBeta](https://github.com/fastnlp/fitlog/releases/tag/WindowsBeta)，但目前进行的测试还不是很多，欢迎您进行试用。

您可以在命令行中使用 `pip3 install git+https://github.com/fastnlp/fitlog.git@beta` 进行安装。
目前在 Git Bash 中可以获得完整的体验，在 CMD 和 PowerShell 中可能无法显示设定的颜色， 我们还没有测试 Windows 上的其它 Bash 。

**Comment by WillQvQ** [comment]
> > > 请问如何在windows上查看远程服务器启动的网页服务呢
> > 
> > 
> > 命令行`fitlog log logs`启动后， 输入localhost:5000就可以在浏览器上查看了
> 
> 感谢回复~不过我的代码是运行在远程服务器的docker里，不知道用什么方法可以在本地访问到服务器上启动的web服务呢?

您可以在运行容器时使用类似 `docker run -p 8000:5000 ...` 的形式使用端口映射，其中5000是容器内的端口，8000是宿主机的端口。然后您可以通过访问 {远程服务器 IP}:{宿主机的端口} 的形式访问 fitlog 的网页服务。

**Comment by softhuafei** [comment]
@WillQvQ 我试试，谢谢啦~
