### ISSUE TITLE
请问作图是根据loss.log文件里的数据作图的吗，为什么loss.log里面有数据，但点了最后一列action里的trend看不到loss的图像呢？

### ISSUE THREAD

**Issue by yqy2001** [fastnlp/fitlog#11]

**Comment by yhcc** [comment]
是的，是根据loss.log到数据作图的。你方便把这条你看不到loss的log文件整体发给我们吗？只需要你看不到loss的这一个folder下的内容即可。

**Comment by yqy2001** [comment]
folder






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yhcc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 下午4:12
收件人:&nbsp;"fastnlp/fitlog"<fitlog@noreply.github.com&gt;;
抄送:&nbsp;"。。。。"<178526723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fastnlp/fitlog] 请问作图是根据loss.log文件里的数据作图的吗，为什么loss.log里面有数据，但点了最后一列action里的trend看不到loss的图像呢？ (#11)





 
是的，是根据loss.log到数据作图的。你方便把这条你看不到loss的log文件整体发给我们吗？只需要你看不到loss的这一个folder下的内容即可。

**Comment by yqy2001** [comment]
啊谢谢呀，麻烦了，我是win10，用的fitlog log logs/ --ip 127.0.0.1命令
打开trend是这样：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yhcc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 下午4:12
收件人:&nbsp;"fastnlp/fitlog"<fitlog@noreply.github.com&gt;;
抄送:&nbsp;"。。。。"<178526723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fastnlp/fitlog] 请问作图是根据loss.log文件里的数据作图的吗，为什么loss.log里面有数据，但点了最后一列action里的trend看不到loss的图像呢？ (#11)





 
是的，是根据loss.log到数据作图的。你方便把这条你看不到loss的log文件整体发给我们吗？只需要你看不到loss的这一个folder下的内容即可。

**Comment by yqy2001** [comment]
[log_20200503_064956.zip](https://github.com/fastnlp/fitlog/files/4569899/log_20200503_064956.zip)
啊谢谢呀，麻烦了，我是win10，用的fitlog log logs/ --ip 127.0.0.1命令
打开trend是这样：
![image](https://user-images.githubusercontent.com/55196500/80910638-7f956f80-8d63-11ea-8528-044a4d6b64d1.png)

**Comment by yhcc** [comment]
原因是由于你的loss是一个tensor，fitlog错误识别了其类型（是一个记录的时候的bug）。你在存loss的时候需要传入一个float，通过tensor.item()传如数据。

**Comment by yqy2001** [comment]
好的，已解决，多谢
