### ISSUE TITLE
可以自动搜索参数吗

### ISSUE THREAD

**Issue by unikcc** [fastnlp/fitlog#15]
比如在config里指定dropout = [0.1, 0.2, 0.3]
在代码里使用dropout = fitlog.config['dropout']
然后执行代码，自动执行三次试验，无需手动写循环，或者每次手动改变参数

**Comment by yhcc** [comment]
目前fitlog不支持这个功能，fitlog只是一个单纯的记录工具，需要您自己写一个for循环调用。不过我们有个内部工具fitsearch可以达到这个目的，目前在考虑整合到fitlog中，欢迎您持续关注fitlog。
