### ISSUE TITLE
多个log的曲线显示

### ISSUE THREAD

**Issue by jnjaby** [fastnlp/fitlog#16]
目前只能显示单个log的不同metric，实际上往往需要显示同一metric在不同log下对比，请问如何操作？

**Comment by yhcc** [comment]
现在还不支持

**Comment by yhcc** [comment]
好吧，还是架不住需求，这周应该这个功能就会开发出来。

**Comment by yhcc** [comment]
肝了三天，终于搞完了。现在可以通过 pip install git+https://github.com/fastnlp/fitlog安装最新版本试一试。
