### ISSUE TITLE
[feature request] 多个project的实验记录之间合并

### ISSUE THREAD

**Issue by JiangPQ** [fastnlp/fitlog#17]
经常遇到很多个人用同一份code的不同branch在不同的机器上同时进行不同实验的情况，fitlog有没有打算加入合并多个project实验结果的功能？这样可以把大家的log合并在一起观察结果。

**Comment by yhcc** [comment]
你直接把不同机器的logs文件下载到一起就好了。logs folder下面每个类似log_20200129_163601的就是一条实验记录。
