### ISSUE TITLE
无法打开网页

### ISSUE THREAD

**Issue by XiaoJiNu** [fastnlp/fitlog#19]
您好，我用fitlog log logs命令后没有网页显示，没有任何响应，输入localhost:5000后也一样。
参考issue中的方法用fitlog log logs/ --ip 127.0.0.1也不行。
重新安装beta版本也不行，一样没有显示。
![图片](https://user-images.githubusercontent.com/30587645/84335034-74d1c400-abc6-11ea-9243-99824e6efa50.png)

请问是什么原因？
我的环境是win10，python3.7

**Comment by yhcc** [comment]
尝试访问0.0.0.0:5000, 127.0.0.1:5000呢？
