### ISSUE TITLE
fitlog revert 无法正确回退代码（版本：0.5.8）

### ISSUE THREAD

**Issue by yubowen-ph** [fastnlp/fitlog#23]
您好：
         我在代码起始位置加入fitlog.commit(__file__)后，按照fitlog revert xxx的方式回退代码，提升 Your code is reverted to /data/yubowen/experiments/NA_revert，但是在NA_revert文件夹中并没有代码，请问是什么问题呢？

**Comment by WillQvQ** [comment]
感谢你的Issue，这是我们的一个 bug。在当前的情况下，你还需要在 /data/yubowen/experiments/NA_revert 目录下使用命令 git reset --hard HEAD 才能获得正确的代码（我们的操作只完成了重设 HEAD 的操作）。

不过，我们也刚刚修复了这个 bug。你可以从 github 上安装最新的 fitlog 以获得修复后的工具。
@yubowen-ph

**Comment by yubowen-ph** [comment]
感谢回复！已更新到新版，使用体验很好
