### ISSUE TITLE
fit_msg、git_msg和memo的edit无法保存

### ISSUE THREAD

**Issue by yubowen-ph** [fastnlp/fitlog#24]
您好：
网页界面上对fit_msg、git_msg和memo进行edit后提示update successfully，但是刷新网页后还是edit之前的状态，有什么特殊操作需要进行么？

**Comment by yubowen-ph** [comment]
经过尝试，发现需要点击右上角的save图标才可以保存，但是有点隐蔽，可否考虑自动保存或者在教程中进行提示

**Comment by WillQvQ** [comment]
你提出的建议非常好，我们也在找机会补全教程。不过由于网页工具功能众多，我们受限于学校课程和科研工作暂时还没有时间进行网页工具的完整教程编写。

**Comment by yhcc** [comment]
这里是估计如此设计的，因为我们考虑到有时候可能会误操作（例如delete了不想delete的log、添加了不想添加的信息），想要回退的话，只需要刷新一下页面就回退了。嗯，没有使用说明确实很难顶。
