### ISSUE TITLE
commit多个文件 & 与git混合使用

### ISSUE THREAD

**Issue by huhk-sysu** [fastnlp/fitlog#3]
您好，我在使用fitlog中产生了一些疑问，烦请解答：

1. 文档的例子是针对一个main.py进行commit的，如果我在实验中对几个文件都进行了修改，是否需要对所有修改的文件（或者说，所有我希望fitlog记录修改的文件）都进行fitlog.commit呢？
2. fitlog如何和普通的git混合使用呢？我能或者有需要额外使用git进行add、commit这样的操作吗？还是说我只需要用fitlog进行commit就可以了？

谢谢！

**Comment by WillQvQ** [comment]
非常抱歉，我们的开发团队暂时还没有给出一个详细的教程。您的问题的回答如下：
1. fitlog是会自动保存 **工作目录** 及其子目录中所有 **符合要求的文件** 。 **工作目录** 的定义是包含 .fitlog 文件夹的目录， .fitlog 是通过fitlog的[命令行工具](https://fitlog.readthedocs.io/zh/latest/user/command_line.html)初始化项目生成的。**符合要求的文件** 是指在 .fitconfig 文件中指定的被监控的文件类型，默认包含 .py 文件。所以，您只需在 **工作目录** 内的一个文件中执行 fitlog.commit 即可。
2. fitlog和普通的git互相不影响，fitlog的[命令行工具](https://fitlog.readthedocs.io/zh/latest/user/command_line.html)会默认生成一个同时包含fitlog和标准git的工作目录。用户可以通过参数选择不生成标准git，因为仅仅使用fitlog也可以保证自己代码的历史版本被记录。但我们推荐你同时使用fitlog和标准git，并通过git记录自己代码的关键版本。

您还可以继续阅读fitlog文档的API部分：https://fitlog.readthedocs.io/zh/latest/fitlog.html#

**Comment by huhk-sysu** [comment]
谢谢，我基本了解了。
