### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by dongZheX** [fastnlp/fitlog#33]
首先感谢作者，fitlig真的很好用，下面是我在使用中遇到的一个小bug。
当我使用argsparse传入列表参数时:
parser.add_argument("--hidden_dim",type=int,nargs='+')
此时type(args.hidden_dim)是list,但是执行fitlog.add_hyper(args)后，type(args.hidden_dim)为str,如果此时将次参数传入模型会造成错误。虽然这个bug可以规避，但是感觉也算是个小问题。

**Comment by yhcc** [comment]
感谢你的肯定～你说的这个bug我们之前也遇到了，现在的版本应该已经解决这个问题了。可以通过pip uninstall fitlog先卸载老的fitlog，然后通过 pip install git+https://github.com/fastnlp/fitlog 下载最新的版本。
