### ISSUE TITLE
UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by hmtbgc** [fastnlp/fitlog#4]
When I followed the tutorial of fitlog, I met a bug at step3.
After I typed "fitlog log logs", I came across an error 
"**UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 36: illegal multibyte sequence**"
at 
"**../fitlog/fastserver/server/log_config_parser.py", line 1042, in _read
    for lineno, line in enumerate(fp, start=1):**
So I modified the encoding at line 682.
Is there any better solution?

**Comment by yhcc** [comment]
应该是由于open文件的时候我们没有加encoding参数，之后我们会检查下把它加进去。
