### ISSUE TITLE
是否支持自定义logging的级别？

### ISSUE THREAD

**Issue by zzysay** [fastnlp/fitlog#42]
您好，我看到源码中是在create_log_files()里定义了logging的级别，请问是否支持用户再次自定义这一级别呢？因为我不太希望在训练过程中出现很多行loss，因为tqdm已经可以满足这一需求。
谢谢！

**Comment by zzysay** [comment]
我尝试按照name把这些logger取出来再次设置logging的级别，但是似乎并没有什么效果

**Comment by choosewhatulike** [comment]
```
from fastNLP import logger
logger.setLevel('WARN')
```
试一试这样呢？

**Comment by yhcc** [comment]
您是指出现了他把loss打印出来了，对吧？可以尝试升级一下fitlog解决这个问题pip install git+https://gitee.com/fastnlp/fitlog

**Comment by zzysay** [comment]
升级就可以了，谢谢~~
