### ISSUE TITLE
能否选择直接使用.git做管理

### ISSUE THREAD

**Issue by kylinat2688** [fastnlp/fitlog#45]
是否可以有个选项直接使用.git做版本管理，不用.fitlog，这样更加简单一些，我也可以将logs和.fitconfig这些文件一起添加到git上去，如果放在.fitlog中不能提交到git上去，后面如果丢失，实验记录就丢了

**Comment by WillQvQ** [comment]
fitlog 和 git 的是可以同时使用。实际上，当你使用 fitlog init 命令初始化项目时，工具就会帮你同时初始化git。你可以在使用 .fitlog 的同时手动 commit 并上传到你的远程仓库中。

**Comment by WillQvQ** [comment]
您可以参考这个文档 https://fitlog.readthedocs.io/zh/latest/user/command_line.html#fitlog-init

**Comment by kylinat2688** [comment]
tks
