### ISSUE TITLE
文档中提供的例子无法运行

### ISSUE THREAD

**Issue by RingoTC** [fastnlp/fitlog#50]
![image](https://user-images.githubusercontent.com/6525061/111999985-7d452b00-8b58-11eb-8895-510fb0863991.png)
应该是这段代码出了问题
![image](https://user-images.githubusercontent.com/6525061/112000196-b7163180-8b58-11eb-9613-1c164b2f5cbb.png)
在
![image](https://user-images.githubusercontent.com/6525061/112000254-c72e1100-8b58-11eb-9df5-b7cf9ca74b75.png)
传入的参数已经是包括文件名的路径了

**Comment by yhcc** [comment]
可能是由于没有运行Step2中的代码导致的没有log文件生成？您可以通过查看logs下是否有文件夹来判断，正常情况下应该有类似于log_20210321_222930这种命名的文件夹。

**Comment by RingoTC** [comment]
原来那个main文件是需要执行的...
