### ISSUE TITLE
请问不可以用多进程的技术问题是哪方面呢？

### ISSUE THREAD

**Issue by saladcat** [fastnlp/fitlog#53]
比较好奇，多进程还是挺需要的，特别是搜参数的时候

**Comment by yhcc** [comment]
你是指通过多进程开subprocess.Popen命令行来弄的，还是直接multiprocessing的多进程的跑呀？

**Comment by saladcat** [comment]
![image](https://user-images.githubusercontent.com/22851795/143455791-e522b20c-1460-4ee0-9c9e-3083603d478b.png)
这里提到不能用multiprocesing跑
看您的意思是可以用Popen运行吗？
能否提供一段简单样例呢？下午的时候试了一下Popen好像也不行？

**Comment by yhcc** [comment]
可以通过Popen使用的
```
from multiprocessing import Popen

for lr in [1e-5, 2e-5]:
  Popen(f'python run.py --lr {lr}', shell=True)
```
这样是可以的。因为不同运行的进程是不共享fitlog的，就是可以的。如果是multiprocessing的Pool之类的在同一个python文件中运行就不行。

**Comment by saladcat** [comment]
解决了我的问题，太感谢了

**Comment by dennislx** [comment]
> 是可以的。如果是multiprocessing的Pool之类的在同一个python文件中运行就不行。

你好，首先这真的是一个很棒的实验管理软件，简单又实用. 介意分享一下为何不把`fitlog`给包装成一个类(从而可以实例化), 而是直接调用模块函数的方式实现实验记录吗? 我的应用场景是多线程跑不同的模型参数, 然而现在fitlog把所有线程的实验结果都记录在同一个文件夹里了。

使用`Popen`是一种思路，但我比较好奇为何不让fitlog是可实例化的对象，是因为这样会和版本管理产生冲突吗?

https://github.com/fastnlp/fitlog/blob/57ce76ab131e6cc9c5aa2bdb938184e472769927/fitlog/__init__.py#L78-L85
