### ISSUE TITLE
如何查看fitlog下自动commit的代码变动

### ISSUE THREAD

**Issue by woocoder** [fastnlp/fitlog#56]
工具非常赞，提高了我的调参效率
想请问是否可以直接在网页上查看fitlog.commit的代码版本变动？如果目前工具不支持的话，有什么方案可以推荐吗？

**Comment by yhcc** [comment]
目前没有，大概只有你reset之后，在reset的那个文件夹那里，可以通过git log查看一下了（reset的目录里面的git记录就是fitlog的git记录
