### ISSUE TITLE
请问如何将for循环和fitlog结合起来

### ISSUE THREAD

**Issue by TreezzZ** [fastnlp/fitlog#6]
比如我现在有个超参数alpha想从[1, 2...,10]中搜索，我写了一个for循环给我的算法传参数
for alpha in range(1, 11):
    fitlog.add_hyper(alpha, 'alpha')
    train(..., alpha)
`
在web页面里我发现下一个循环的数值会替换上一次的，没有办法得到10个值的结果。

**Comment by yhcc** [comment]
fitlog.set_log_dir(new_log=True)就会自动从一个新的log文件开始记录log。
