### ISSUE TITLE
 http://0.0.0.0:5000/ 打不开

### ISSUE THREAD

**Issue by dawnlh** [fastnlp/fitlog#7]
fitlog log logs运行正常，但是 http://0.0.0.0:5000/ 打不开，指定其他端口也没用，请问可能是什么原因呢？有可能是这个吗 https://www.cnblogs.com/squirrel2300/p/6925446.html

**Comment by yhcc** [comment]
试一下fitlog log logs/ --ip 127.0.0.1呢，我没在windows上测试过

**Comment by dawnlh** [comment]
嗯嗯，win10可以的，感谢~ 因为文档里面没有说又 --ip这个参数所以我没试，建议更新下文档关于windows的ip~
Usage:
    fitlog log <log-dir> [--log-config-name=L] [--port=P] [--standby-hours=S]

Arguments:
    log-dir                 Where to find logs.

Options:
    -h --help               This is a command to start fitlog server to visualize logs.
    -l=L --log-config-name  Log server config name. Must under the folder of <log-dir>. [default: default.cfg]
    -p=P --port             Which port to start to looking for usable port.[default: 5000]
    -s=S --standby-hours    How long to wait before the server . [default: 48]

**Comment by yhcc** [comment]
太好了，解决了就好。不过你已经发现了fitlog最大的问题就是 没有文档。。。。。哈哈哈哈
